- name: Configuration of users and hosts
  hosts: archlinuxarm
  vars:
    ansible_become: yes

  tasks:
    - name: Set hostname
      # not ansible.builtin.hostname, since the systemd way will escape the chroot
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: '.*'
        line: '{{hostname}}'
      tags: hostname

    - name: Add user to groups
      ansible.builtin.user:
        user: '{{username}}'
        groups: wheel, uucp
      tags: user
